In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

import plotly.express as px
pd.options.plotting.backend = 'plotly'

In [38]:
recipes = pd.read_csv("RAW_recipes.csv")
ratings = pd.read_csv("RAW_interactions.csv")

In [39]:
ratings

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."
...,...,...,...,...,...
1132362,116593,72730,2003-12-09,0,Another approach is to start making sauce with...
1132363,583662,386618,2009-09-29,5,These were so delicious! My husband and I tru...
1132364,157126,78003,2008-06-23,5,WOW! Sometimes I don't take the time to rate ...
1132365,53932,78003,2009-01-11,4,Very good! I used regular port as well. The ...
1132366,2001868099,78003,2017-12-18,5,I am so glad I googled and found this here. Th...

In [40]:
# Merge dataframes
merged = recipes.merge(ratings, how="left", left_on="id", right_on="recipe_id")
merged['rating'] = merged['rating'].replace(0, np.nan)

In [41]:
merged

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,user_id,recipe_id,date,rating,review
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,4470,137739,2006-02-18,5.0,I used an acorn squash and recipe#137681 Swee...
1,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,593927,137739,2010-08-21,5.0,This was a nice change. I used butternut squas...
2,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,178427,137739,2011-12-05,5.0,Excellent recipe! I used butternut squash and ...
3,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6,28603,31490,2002-08-19,NaN,"Have not tried this, but it sounds delicious. ..."
4,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6,346277,31490,2006-08-27,5.0,This recipe was wonderful. Instead of using t...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1132362,zydeco ya ya deviled eggs,308080,40,37779,2008-06-07,"['60-minutes-or-less', 'time-to-make', 'course...","[59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]",7,"['in a bowl , combine the mashed yolks and may...","deviled eggs, cajun-style","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8,844554,308080,2009-10-14,5.0,These were very good. I meant to add some jala...
1132363,cookies by design cookies on a stick,298512,29,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[188.0, 11.0, 57.0, 11.0, 7.0, 21.0, 9.0]",9,['place melted butter in a large mixing bowl a...,"i've heard of the 'cookies by design' company,...","['butter', 'eagle brand condensed milk', 'ligh...",10,804234,298512,2008-05-02,1.0,I would rate this a zero if I could. I followe...
1132364,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,866651,298509,2008-06-19,1.0,This recipe tastes nothing like the Cookies by...
1132365,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,1546277,298509,2010-02-08,5.0,"yummy cookies, i love this recipe me and my sm..."
1132366,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,1803287907,298509,2014-11-01,NaN,I work at a Cookies By Design and can say this...

In [42]:
# Find average rating per recipe and add to recipes dataframe
avg_ratings = merged.groupby('id')['rating'].mean()
avg_ratings_df = avg_ratings.reset_index().rename(columns={'rating': 'avg_rating'})

recipes = recipes.merge(avg_ratings_df, how='left', on='id')

In [43]:
# Finding columns with missing vals
nan_columns = recipes.columns[recipes.isnull().any()]

print(nan_columns)

Index(['name', 'description', 'avg_rating'], dtype='object')

In [44]:
# Fill missing descriptions with a placeholder
recipes['description'] = recipes['description'].fillna('No description available')

print(f"Number of missing descriptions after filling: {recipes['description'].isna().sum()}")

Number of missing descriptions after filling: 0

In [45]:
# Check for missing columns
nan_columns = recipes.columns[recipes.isnull().any()]

print(nan_columns)

Index(['name', 'avg_rating'], dtype='object')

In [46]:
# Check missing values in Average Rating
recipes[recipes['avg_rating'].isna()]

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,avg_rating
63,more more apple pear jigglers,63593,125,47858,2003-06-02,"['weeknight', 'time-to-make', 'main-ingredient...","[22.9, 1.0, 5.0, 0.0, 1.0, 3.0, 0.0]",6,"['in a food processor or blender , process the...",it's a fun finger food for infants and toddler...,"['unflavored gelatin', 'milk', 'cream cheese',...",6,NaN
64,mr grant you took half veal prince orloff,43164,120,28201,2002-10-14,"['weeknight', 'time-to-make', 'course', 'main-...","[510.6, 50.0, 10.0, 21.0, 90.0, 70.0, 1.0]",26,"['preheat oven to 325', 'dry the veal on paper...",i couldn't resist! named in honor of one of my...,"['veal roast', 'butter', 'oil', 'carrots', 'on...",11,NaN
74,philly waldorf salad,5060,60,1534,1999-12-01,"['60-minutes-or-less', 'time-to-make', 'course...","[180.7, 22.0, 29.0, 3.0, 6.0, 33.0, 3.0]",4,"['combine softened cream cheese , orange juice...",No description available,"['philadelphia cream cheese', 'orange juice', ...",7,NaN
109,zupa ze swiezych grzybow polish mushroom soup,105069,40,51109,2004-11-30,"['60-minutes-or-less', 'time-to-make', 'course...","[176.6, 19.0, 11.0, 26.0, 12.0, 37.0, 3.0]",10,"['wash and coarsely chop mushrooms', 'saute ov...",posted in response to a request. from my grand...,"['wild mushrooms', 'onions', 'butter', 'lemon,...",10,NaN
138,lplermagronen,455351,55,1308592,2011-05-07,"['60-minutes-or-less', 'time-to-make', 'prepar...","[651.8, 33.0, 12.0, 16.0, 32.0, 63.0, 33.0]",15,['heat oven to 375f set a large pot of salted ...,"known as swiss mac n cheese, älplermagronen wa...","['potato', 'penne pasta', 'onions', 'butter', ...",8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
231537,zucchini oat bread,292835,105,324390,2008-03-19,"['time-to-make', 'course', 'main-ingredient', ...","[4588.6, 226.0, 1501.0, 141.0, 178.0, 213.0, 2...",19,"['preheat oven to 350 degrees f', 'lightly coa...",the bh&g $400 winner of the bread and rolls ca...,"['nonstick cooking spray', 'sugar', 'ground ci...",15,NaN
231580,zuppa de clams or mussels,88280,40,133933,2004-04-05,"['60-minutes-or-less', 'time-to-make', 'course...","[358.1, 56.0, 21.0, 0.0, 3.0, 25.0, 2.0]",13,['wash and dry the clams and soak them in a la...,"this is a delicious italian first course soup,...","['baby clams', 'salt and pepper', 'olive oil',...",8,NaN
231591,zuppa inglese,26261,120,34146,2002-04-24,"['weeknight', 'time-to-make', 'course', 'main-...","[453.4, 12.0, 209.0, 4.0, 20.0, 19.0, 24.0]",36,"['preheat oven to 375f', 'in a large bowl , be...",an italian cake usually served on special occa...,"['rum', 'creme de cacao', 'candied fruit', 'eg...",13,NaN
231607,zurichgeschnetzeltes or diced chicken,16940,11,10404,2002-01-08,"['15-minutes-or-less', 'time-to-make', 'course...","[592.2, 55.0, 6.0, 7.0, 110.0, 68.0, 1.0]",7,['heat oil in a medium fry pan over medium hig...,i found this recipe on the net per a recipe re...,"['chicken breasts', 'mushrooms', 'lemon juice'...",7,NaN
231628,zydeco green beans,185979,20,145599,2006-09-13,"['30-minutes-or-less', 'time-to-make', 'course...","[103.1, 2.0, 39.0, 97.0, 11.0, 0.0, 7.0]",6,"['into each of six sterile pint mason jars , p...",haricots verts are very slender french green b...,"['garlic cloves', 'yellow mustard seeds', 'fre...",8,NaN

We would try to fill in missingness here, but these recipes have no ratings, and such cannot be predicted.

In [47]:
# Convert nutrition column from string to list
recipes['nutrition'] = recipes['nutrition'].apply(eval)

In [48]:
# Convert nutrition list into separate columns
nutrition_df = pd.DataFrame(recipes['nutrition'].tolist(), 
                          columns=['calories', 'total fat (PDV)', 'sugar (PDV)', 'sodium (PDV)', 'protein (PDV)', 'saturated fat (PDV)', 'carbohydrates (PDV)'])

# Add the nutrition columns to the original dataframe
recipes = pd.concat([recipes, nutrition_df], axis=1)

In [49]:
recipes

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,avg_rating,calories,total fat (PDV),sugar (PDV),sodium (PDV),protein (PDV),saturated fat (PDV),carbohydrates (PDV)
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,5.000000,51.5,0.0,13.0,0.0,2.0,0.0,4.0
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6,4.666667,173.4,18.0,0.0,17.0,22.0,35.0,1.0
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13,4.000000,269.8,22.0,32.0,48.0,39.0,27.0,5.0
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11,4.500000,368.1,17.0,10.0,2.0,14.0,8.0,20.0
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8,5.000000,352.9,1.0,337.0,23.0,3.0,0.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231632,zydeco soup,486161,60,227978,2012-08-29,"['ham', '60-minutes-or-less', 'time-to-make', ...","[415.2, 26.0, 34.0, 26.0, 44.0, 21.0, 15.0]",7,"['heat oil in a 4-quart dutch oven', 'add cele...",this is a delicious soup that i originally fou...,"['celery', 'onion', 'green sweet pepper', 'gar...",22,5.000000,415.2,26.0,34.0,26.0,44.0,21.0,15.0
231633,zydeco spice mix,493372,5,1500678,2013-01-09,"['15-minutes-or-less', 'time-to-make', 'course...","[14.8, 0.0, 2.0, 58.0, 1.0, 0.0, 1.0]",1,['mix all ingredients together thoroughly'],this spice mix will make your taste buds dance!,"['paprika', 'salt', 'garlic powder', 'onion po...",13,5.000000,14.8,0.0,2.0,58.0,1.0,0.0,1.0
231634,zydeco ya ya deviled eggs,308080,40,37779,2008-06-07,"['60-minutes-or-less', 'time-to-make', 'course...","[59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]",7,"['in a bowl , combine the mashed yolks and may...","deviled eggs, cajun-style","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8,5.000000,59.2,6.0,2.0,3.0,6.0,5.0,0.0
231635,cookies by design cookies on a stick,298512,29,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[188.0, 11.0, 57.0, 11.0, 7.0, 21.0, 9.0]",9,['place melted butter in a large mixing bowl a...,"i've heard of the 'cookies by design' company,...","['butter', 'eagle brand condensed milk', 'ligh...",10,1.000000,188.0,11.0,57.0,11.0,7.0,21.0,9.0
231636,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,3.000000,174.9,14.0,33.0,4.0,4.0,11.0,6.0

In [50]:
# Convert times to time series
recipes['submitted'] = pd.to_datetime(recipes['submitted'])

In [51]:
# Head of cleaned dataframe
recipes.head()

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,avg_rating,calories,total fat (PDV),sugar (PDV),sodium (PDV),protein (PDV),saturated fat (PDV),carbohydrates (PDV)
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,5.000000,51.5,0.0,13.0,0.0,2.0,0.0,4.0
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6,4.666667,173.4,18.0,0.0,17.0,22.0,35.0,1.0
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13,4.000000,269.8,22.0,32.0,48.0,39.0,27.0,5.0
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11,4.500000,368.1,17.0,10.0,2.0,14.0,8.0,20.0
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8,5.000000,352.9,1.0,337.0,23.0,3.0,0.0,28.0

In [52]:
# Distribution of average ratings per recipe
fig = px.histogram(
    recipes,
    x='avg_rating',
    nbins=20,
    title='Distribution of Average Recipe Ratings',
    labels={'avg_rating': 'Average Rating'},
    template='plotly_white'
)
fig.update_layout(title_x=0.5)
fig.show()

In [53]:
# Distribution of preparation time for each recipe
fig = px.box(
    recipes[recipes['minutes'] <= 300], # removed extreme outliers
    y='minutes',
    title='Preparation Time Distribution',
    labels={'minutes': 'Preparation Time (minutes)'},
    template='plotly_white',
    color_discrete_sequence=['#EF553B']
)
fig.update_layout(title_x=0.5, width=500, height=800)
fig.show()

In [54]:
# Distribution of calories in recipes
fig = px.histogram(
    recipes[recipes['calories'] <= 3000], # removed outliers
    x='calories',
    nbins=30,
    title='Distribution of Calories in Recipes',
    labels={'calories': 'Calories'},
    template='plotly_white',
    color_discrete_sequence=['#FFA15A']
)
fig.update_layout(title_x=0.5)
fig.show()

In [55]:
# Distribution of protein in recipes
fig = px.histogram(
    recipes[(recipes['protein (PDV)'] <= 100)],  # focus on relevant bin range
    x='protein (PDV)',
    title='Distribution of Protein Values (PDV)',
    labels={'protein (PDV)': 'Protein (% Daily Value)'},
    template='plotly_white',
    color_discrete_sequence=['#00CC96']
)
fig.update_layout(title_x=0.5)
fig.show()

lets look at missingness

In [56]:
print("Average minutes for recipes with missing ratings:", recipes[recipes['avg_rating'].isna()]['minutes'].mean())
print("Average minutes for recipes with non-missing ratings:", recipes[recipes['avg_rating'].notna()]['minutes'].mean())

Average minutes for recipes with missing ratings: 287.32752129978206
Average minutes for recipes with non-missing ratings: 9601.48664989629

In [57]:
recipes = recipes[recipes['minutes'] < 10000]

In [58]:
recipes

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,avg_rating,calories,total fat (PDV),sugar (PDV),sodium (PDV),protein (PDV),saturated fat (PDV),carbohydrates (PDV)
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7,5.000000,51.5,0.0,13.0,0.0,2.0,0.0,4.0
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6,4.666667,173.4,18.0,0.0,17.0,22.0,35.0,1.0
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13,4.000000,269.8,22.0,32.0,48.0,39.0,27.0,5.0
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11,4.500000,368.1,17.0,10.0,2.0,14.0,8.0,20.0
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8,5.000000,352.9,1.0,337.0,23.0,3.0,0.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231632,zydeco soup,486161,60,227978,2012-08-29,"['ham', '60-minutes-or-less', 'time-to-make', ...","[415.2, 26.0, 34.0, 26.0, 44.0, 21.0, 15.0]",7,"['heat oil in a 4-quart dutch oven', 'add cele...",this is a delicious soup that i originally fou...,"['celery', 'onion', 'green sweet pepper', 'gar...",22,5.000000,415.2,26.0,34.0,26.0,44.0,21.0,15.0
231633,zydeco spice mix,493372,5,1500678,2013-01-09,"['15-minutes-or-less', 'time-to-make', 'course...","[14.8, 0.0, 2.0, 58.0, 1.0, 0.0, 1.0]",1,['mix all ingredients together thoroughly'],this spice mix will make your taste buds dance!,"['paprika', 'salt', 'garlic powder', 'onion po...",13,5.000000,14.8,0.0,2.0,58.0,1.0,0.0,1.0
231634,zydeco ya ya deviled eggs,308080,40,37779,2008-06-07,"['60-minutes-or-less', 'time-to-make', 'course...","[59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]",7,"['in a bowl , combine the mashed yolks and may...","deviled eggs, cajun-style","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8,5.000000,59.2,6.0,2.0,3.0,6.0,5.0,0.0
231635,cookies by design cookies on a stick,298512,29,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[188.0, 11.0, 57.0, 11.0, 7.0, 21.0, 9.0]",9,['place melted butter in a large mixing bowl a...,"i've heard of the 'cookies by design' company,...","['butter', 'eagle brand condensed milk', 'ligh...",10,1.000000,188.0,11.0,57.0,11.0,7.0,21.0,9.0
231636,cookies by design sugar shortbread cookies,298509,20,506822,2008-04-15,"['30-minutes-or-less', 'time-to-make', 'course...","[174.9, 14.0, 33.0, 4.0, 4.0, 11.0, 6.0]",5,"['whip sugar and shortening in a large bowl , ...","i've heard of the 'cookies by design' company,...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,3.000000,174.9,14.0,33.0,4.0,4.0,11.0,6.0

In [59]:
print("Average minutes for recipes with missing ratings:", recipes[recipes['avg_rating'].isna()]['minutes'].mean())
print("Average minutes for recipes with non-missing ratings:", recipes[recipes['avg_rating'].notna()]['minutes'].mean())

Average minutes for recipes with missing ratings: 104.81286084013537
Average minutes for recipes with non-missing ratings: 80.20416431045452

# Prediction Problem

Can we predict rating from user activity?